### PR TITLE
new feed prio, datapoint changes

### PR DESCRIPTION
**Pull request by foxthefox**
hence this package was mentioned at homeassistant, I sneaked into it and I thought that I can contribute with my work at an iobroker implementation.
I do not own homie, therefore I couldn't test my changes.

one new entity is added for powerstream -> feed priority
some changes to the datapoints might be considered (mainly "division")

I am not so experienced with python, but important to mention is the behaviour for supply/feedPriority.
The true value is send with 1 in protobuf with datalen=2, contrarily the false is send without data portion in the protobuf and datalen is omitted. I couldn't see if it is realized this way.

### CODE REVIEW

**Comment by peuter** [comment]
Thanks for the contribution, I will try to test that on the weekend. Could you please changes you editors indentation (tabSize) to 4 spaces for the json files. That would make the diffs way more readable. I just added my latest local changes als also corrected the indentation of the delta-max.json to 4. That change leads to merge conflicts with your changes, They should be gone, when you use the same indentation.

And just for clarification: Homie is no device / hardware you can own. Its just a standard that describes a scheme how to publish smarthome devices to different MQTT topics. If you have a client that implements this standard you can communicate with the homie devices. openHAB supports homie, and thats why I wrote this library. They are automatically discovered by openHAB and can add them to my system easily. I don't know how the homie support is for other smarthome systems though.

**Comment by foxthefox** [comment]
I hope that now the identation issue is gone, I updated the conflict with the changes and hopefully kept the formatting

**Comment by peuter** [comment]
The ncurses.json has still the wrong indentation and the diff view here on the gitub page for the delta-max.json got event worse, though I have no idea why.

**Comment by foxthefox** [comment]
the ncurses I did not touch again, I will also correct it there.
I think I create a new PR, with hopefully better visibility of changes

**Pull request closed without merging**
